"""empty message

Revision ID: 0251eb11b61b
Revises: d6304a5d4c0d
Create Date: 2026-09-21 11:45:12.681820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0251eb11b61b'
down_revision = 'd6304a5d4c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rastreamento_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('prefeitura_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('reportado_em', sa.DateTime(), nullable=False),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.Column('provedor', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('chave_fixture', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['prefeituras.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rastreamento_alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_chave_fixture'), ['chave_fixture'], unique=True)
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_prefeitura_id'), ['prefeitura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_provedor'), ['provedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_reportado_em'), ['reportado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_resolvido'), ['resolvido'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_severidade'), ['severidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_alertas_veiculo_id'), ['veiculo_id'], unique=False)
        batch_op.create_index('ix_rastreamento_alertas_veiculo_reportado', ['veiculo_id', 'reportado_em'], unique=False)

    op.create_table('rastreamento_historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('prefeitura_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('velocidade_kmh', sa.Float(), nullable=True),
    sa.Column('ignicao', sa.Boolean(), nullable=True),
    sa.Column('hodometro_km', sa.Float(), nullable=True),
    sa.Column('reportado_em', sa.DateTime(), nullable=False),
    sa.Column('provedor', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('chave_fixture', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['prefeituras.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rastreamento_historicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rastreamento_historicos_chave_fixture'), ['chave_fixture'], unique=True)
        batch_op.create_index(batch_op.f('ix_rastreamento_historicos_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_historicos_prefeitura_id'), ['prefeitura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_historicos_provedor'), ['provedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_historicos_reportado_em'), ['reportado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_historicos_veiculo_id'), ['veiculo_id'], unique=False)
        batch_op.create_index('ix_rastreamento_historicos_veiculo_reportado', ['veiculo_id', 'reportado_em'], unique=False)

    op.create_table('rastreamento_posicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('prefeitura_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('velocidade_kmh', sa.Float(), nullable=True),
    sa.Column('ignicao', sa.Boolean(), nullable=True),
    sa.Column('hodometro_km', sa.Float(), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('reportado_em', sa.DateTime(), nullable=False),
    sa.Column('provedor', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('chave_fixture', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['prefeituras.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rastreamento_posicoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rastreamento_posicoes_chave_fixture'), ['chave_fixture'], unique=True)
        batch_op.create_index(batch_op.f('ix_rastreamento_posicoes_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_posicoes_prefeitura_id'), ['prefeitura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_posicoes_provedor'), ['provedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_posicoes_reportado_em'), ['reportado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_rastreamento_posicoes_veiculo_id'), ['veiculo_id'], unique=False)
        batch_op.create_index('ix_rastreamento_posicoes_veiculo_reportado', ['veiculo_id', 'reportado_em'], unique=False)

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quadra_confirmada_admin', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('quadra_visualizada_admin', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('quadra_visualizada_admin_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_solicitacoes_quadra_confirmada_admin'), ['quadra_confirmada_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_quadra_visualizada_admin'), ['quadra_visualizada_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_quadra_visualizada_admin_em'), ['quadra_visualizada_admin_em'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_quadra_visualizada_admin_em'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_quadra_visualizada_admin'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_quadra_confirmada_admin'))
        batch_op.drop_column('quadra_visualizada_admin_em')
        batch_op.drop_column('quadra_visualizada_admin')
        batch_op.drop_column('quadra_confirmada_admin')

    with op.batch_alter_table('rastreamento_posicoes', schema=None) as batch_op:
        batch_op.drop_index('ix_rastreamento_posicoes_veiculo_reportado')
        batch_op.drop_index(batch_op.f('ix_rastreamento_posicoes_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_posicoes_reportado_em'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_posicoes_provedor'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_posicoes_prefeitura_id'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_posicoes_is_demo'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_posicoes_chave_fixture'))

    op.drop_table('rastreamento_posicoes')
    with op.batch_alter_table('rastreamento_historicos', schema=None) as batch_op:
        batch_op.drop_index('ix_rastreamento_historicos_veiculo_reportado')
        batch_op.drop_index(batch_op.f('ix_rastreamento_historicos_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_historicos_reportado_em'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_historicos_provedor'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_historicos_prefeitura_id'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_historicos_is_demo'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_historicos_chave_fixture'))

    op.drop_table('rastreamento_historicos')
    with op.batch_alter_table('rastreamento_alertas', schema=None) as batch_op:
        batch_op.drop_index('ix_rastreamento_alertas_veiculo_reportado')
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_tipo'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_severidade'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_resolvido'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_reportado_em'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_provedor'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_prefeitura_id'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_is_demo'))
        batch_op.drop_index(batch_op.f('ix_rastreamento_alertas_chave_fixture'))

    op.drop_table('rastreamento_alertas')
    # ### end Alembic commands ###
