"""novo_drone_monitoramneto

Revision ID: 10995bc0178b
Revises: cc0e21916d4c
Create Date: 2026-03-03 09:15:29.932165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10995bc0178b'
down_revision = 'cc0e21916d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drone_monitoramento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drone_monitoramento_renomacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drone_monitoramento_modelo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drone_monitoramento_numero_serie', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drone_monitoramento_registro_anatel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('drone_monitoramento_registro_anac', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_concluido_em'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_formulario_preenchido_em'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_status_fluxo'))
        batch_op.drop_index(batch_op.f('ix_os_fluxo'))
        batch_op.create_index(batch_op.f('ix_ordens_servico_drone_monitoramento_id'), ['drone_monitoramento_id'], unique=False)
        batch_op.create_foreign_key(None, 'drones', ['drone_monitoramento_id'], ['id'])
        batch_op.drop_column('formulario_preenchido_em')
        batch_op.drop_column('concluido_em')
        batch_op.drop_column('status_fluxo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_fluxo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('concluido_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('formulario_preenchido_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ordens_servico_drone_monitoramento_id'))
        batch_op.create_index(batch_op.f('ix_os_fluxo'), ['status_fluxo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_status_fluxo'), ['status_fluxo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_formulario_preenchido_em'), ['formulario_preenchido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_concluido_em'), ['concluido_em'], unique=False)
        batch_op.drop_column('drone_monitoramento_registro_anac')
        batch_op.drop_column('drone_monitoramento_registro_anatel')
        batch_op.drop_column('drone_monitoramento_numero_serie')
        batch_op.drop_column('drone_monitoramento_modelo')
        batch_op.drop_column('drone_monitoramento_renomacao')
        batch_op.drop_column('drone_monitoramento_id')

    # ### end Alembic commands ###
