"""criar login das equipes das uvis

Revision ID: 11a05840b7c3
Revises: 045bb998500a
Create Date: 2026-03-04 00:00:11.392499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a05840b7c3'
down_revision = '045bb998500a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipe_uvis_uvis_usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipe_uvis_nome', sa.String(length=100), nullable=True))
        batch_op.create_index('ix_usuario_equipe_uvis', ['equipe_uvis_uvis_usuario_id', 'equipe_uvis_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_equipe_uvis_nome'), ['equipe_uvis_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_equipe_uvis_uvis_usuario_id'), ['equipe_uvis_uvis_usuario_id'], unique=False)
        batch_op.create_unique_constraint('uq_usuario_conta_equipe_uvis', ['equipe_uvis_uvis_usuario_id', 'equipe_uvis_nome'])
        batch_op.create_foreign_key(None, 'usuarios', ['equipe_uvis_uvis_usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_usuario_conta_equipe_uvis', type_='unique')
        batch_op.drop_index(batch_op.f('ix_usuarios_equipe_uvis_uvis_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_equipe_uvis_nome'))
        batch_op.drop_index('ix_usuario_equipe_uvis')
        batch_op.drop_column('equipe_uvis_nome')
        batch_op.drop_column('equipe_uvis_uvis_usuario_id')

    # ### end Alembic commands ###
