"""atualiacao tipo abastecimento

Revision ID: 1330e7e67220
Revises: b8a7d2956a11
Create Date: 2026-03-13 10:35:45.987294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1330e7e67220'
down_revision = 'b8a7d2956a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_abastecimento', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.drop_column('tipo_abastecimento')

    # ### end Alembic commands ###
