"""ajustes_area_restrita

Revision ID: 15d9ec71945b
Revises: 887397110b50
Create Date: 2026-02-06 13:00:59.938596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d9ec71945b'
down_revision = '887397110b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perimetro_planejado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('perimetro_executado', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_column('perimetro_executado')
        batch_op.drop_column('perimetro_planejado')

    # ### end Alembic commands ###
