"""logsVeiculo

Revision ID: 1600d07df8f3
Revises: 9922f618dc90
Create Date: 2026-02-27 11:14:00.637025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1600d07df8f3'
down_revision = '9922f618dc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('km_inicial', sa.Float(), nullable=False),
    sa.Column('km_final', sa.Float(), nullable=False),
    sa.Column('abasteceu', sa.Boolean(), nullable=True),
    sa.Column('litros', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('km_no_abastecimento', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['piloto_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_veiculo_data_registro'), ['data_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_veiculo_piloto_id'), ['piloto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_veiculo_veiculo_id'), ['veiculo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_veiculo_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_logs_veiculo_piloto_id'))
        batch_op.drop_index(batch_op.f('ix_logs_veiculo_data_registro'))

    op.drop_table('logs_veiculo')
    # ### end Alembic commands ###
