"""criação e remoção de campos

Revision ID: 1985ab785618
Revises: fd9c1a47ec4c
Create Date: 2026-03-03 12:09:02.931969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1985ab785618'
down_revision = 'fd9c1a47ec4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_videos_registradas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('quantidade_videos_registradas')

    # ### end Alembic commands ###
