"""empty message

Revision ID: 3c86bbd26982
Revises: b2c3d4e5f6a7
Create Date: 2026-08-03 13:47:39.582419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c86bbd26982'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


# migrations/versions/3c86bbd26982_.py

def upgrade():
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'endereco_bloqueado', 
                sa.Boolean(), 
                nullable=False, 
                server_default=sa.text('false')  # <-- Adicione isso!
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_column('endereco_bloqueado')

    # ### end Alembic commands ###
