"""empty message

Revision ID: 3f82035ba58d
Revises: 5d7e9a1c3b20
Create Date: 2026-09-18 11:04:38.266474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f82035ba58d'
down_revision = '5d7e9a1c3b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.alter_column('tipo_abastecimento',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('agro_flight_kml_routes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('agro_flight_kml_routes_file_sha256_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('agro_flight_kml_routes_flight_record_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('agro_flight_kml_routes_route_code_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_agro_flight_kml_routes_file_sha256'))
        batch_op.create_index(batch_op.f('ix_agro_flight_kml_routes_file_sha256'), ['file_sha256'], unique=True)
        batch_op.drop_index(batch_op.f('ix_agro_flight_kml_routes_flight_record_id'))
        batch_op.create_index(batch_op.f('ix_agro_flight_kml_routes_flight_record_id'), ['flight_record_id'], unique=True)
        batch_op.drop_index(batch_op.f('ix_agro_flight_kml_routes_route_code'))
        batch_op.create_index(batch_op.f('ix_agro_flight_kml_routes_route_code'), ['route_code'], unique=True)

    with op.batch_alter_table('agro_flight_log_imports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('agro_flight_log_imports_file_sha256_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_agro_flight_log_imports_file_sha256'))
        batch_op.create_index(batch_op.f('ix_agro_flight_log_imports_file_sha256'), ['file_sha256'], unique=True)

    with op.batch_alter_table('agro_flight_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('agro_flight_records_fingerprint_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_agro_flight_records_fingerprint'))
        batch_op.create_index(batch_op.f('ix_agro_flight_records_fingerprint'), ['fingerprint'], unique=True)

    with op.batch_alter_table('banco_agro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banco_agro_atualizado_em'), ['atualizado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_banco_agro_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_banco_agro_id'), ['id'], unique=False)

    with op.batch_alter_table('contratos_agro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('contratos_agro_orcamento_agro_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_contratos_agro_orcamento_agro_id'))
        batch_op.create_index(batch_op.f('ix_contratos_agro_orcamento_agro_id'), ['orcamento_agro_id'], unique=True)

    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('denuncias_protocolo_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('denuncias_solicitacao_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_denuncias_atualizado_em'), ['atualizado_em'], unique=False)

    with op.batch_alter_table('equipamentos_agro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipamentos_agro_funcao_operacional'), ['funcao_operacional'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipamentos_agro_registro_anac'), ['registro_anac'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipamentos_agro_registro_anatel'), ['registro_anatel'], unique=False)

    with op.batch_alter_table('estoque_pecas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('estoque_pecas_numero_serie_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_estoque_pecas_numero_serie'))
        batch_op.create_index(batch_op.f('ix_estoque_pecas_numero_serie'), ['numero_serie'], unique=True)
        batch_op.create_index(batch_op.f('ix_estoque_pecas_atualizado_em'), ['atualizado_em'], unique=False)

    with op.batch_alter_table('limpezas_veiculo_alertas_ciencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_limpezas_veiculo_alertas_ciencia_criado_em'), ['criado_em'], unique=False)

    with op.batch_alter_table('ordens_servico_agro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ordens_servico_agro_identificador_os_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_identificador_os'))
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_identificador_os'), ['identificador_os'], unique=True)
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_cidade_operacao'), ['cidade_operacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_cliente_nome'), ['cliente_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_cultura'), ['cultura'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_propriedade_nome'), ['propriedade_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_protocolo'), ['protocolo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_servico'), ['servico'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_uf_operacao'), ['uf_operacao'], unique=False)

    with op.batch_alter_table('ordens_servico_equipe_uvis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_servico_equipe_uvis_id'))

    with op.batch_alter_table('prefeituras', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('prefeituras_nome_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('prefeituras_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_prefeituras_nome'))
        batch_op.create_index(batch_op.f('ix_prefeituras_nome'), ['nome'], unique=True)
        batch_op.drop_index(batch_op.f('ix_prefeituras_slug'))
        batch_op.create_index(batch_op.f('ix_prefeituras_slug'), ['slug'], unique=True)

    with op.batch_alter_table('usuario_presencas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuario_presencas_usuario_id_key'), type_='unique')

    with op.batch_alter_table('watchdog_deploy_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('watchdog_deploy_events_event_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchdog_deploy_events', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('watchdog_deploy_events_event_id_key'), ['event_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('usuario_presencas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('usuario_presencas_usuario_id_key'), ['usuario_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('prefeituras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prefeituras_slug'))
        batch_op.create_index(batch_op.f('ix_prefeituras_slug'), ['slug'], unique=False)
        batch_op.drop_index(batch_op.f('ix_prefeituras_nome'))
        batch_op.create_index(batch_op.f('ix_prefeituras_nome'), ['nome'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('prefeituras_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('prefeituras_nome_key'), ['nome'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('ordens_servico_equipe_uvis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordens_servico_equipe_uvis_id'), ['id'], unique=False)

    with op.batch_alter_table('ordens_servico_agro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_uf_operacao'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_servico'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_protocolo'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_propriedade_nome'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_id'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_cultura'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_cliente_nome'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_cidade_operacao'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_agro_identificador_os'))
        batch_op.create_index(batch_op.f('ix_ordens_servico_agro_identificador_os'), ['identificador_os'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('ordens_servico_agro_identificador_os_key'), ['identificador_os'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('limpezas_veiculo_alertas_ciencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_limpezas_veiculo_alertas_ciencia_criado_em'))

    with op.batch_alter_table('estoque_pecas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_pecas_atualizado_em'))
        batch_op.drop_index(batch_op.f('ix_estoque_pecas_numero_serie'))
        batch_op.create_index(batch_op.f('ix_estoque_pecas_numero_serie'), ['numero_serie'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('estoque_pecas_numero_serie_key'), ['numero_serie'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('equipamentos_agro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipamentos_agro_registro_anatel'))
        batch_op.drop_index(batch_op.f('ix_equipamentos_agro_registro_anac'))
        batch_op.drop_index(batch_op.f('ix_equipamentos_agro_funcao_operacional'))

    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_denuncias_atualizado_em'))
        batch_op.create_unique_constraint(batch_op.f('denuncias_solicitacao_id_key'), ['solicitacao_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('denuncias_protocolo_key'), ['protocolo'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('contratos_agro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_agro_orcamento_agro_id'))
        batch_op.create_index(batch_op.f('ix_contratos_agro_orcamento_agro_id'), ['orcamento_agro_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('contratos_agro_orcamento_agro_id_key'), ['orcamento_agro_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('banco_agro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banco_agro_id'))
        batch_op.drop_index(batch_op.f('ix_banco_agro_criado_em'))
        batch_op.drop_index(batch_op.f('ix_banco_agro_atualizado_em'))

    with op.batch_alter_table('agro_flight_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agro_flight_records_fingerprint'))
        batch_op.create_index(batch_op.f('ix_agro_flight_records_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('agro_flight_records_fingerprint_key'), ['fingerprint'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('agro_flight_log_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agro_flight_log_imports_file_sha256'))
        batch_op.create_index(batch_op.f('ix_agro_flight_log_imports_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('agro_flight_log_imports_file_sha256_key'), ['file_sha256'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('agro_flight_kml_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agro_flight_kml_routes_route_code'))
        batch_op.create_index(batch_op.f('ix_agro_flight_kml_routes_route_code'), ['route_code'], unique=False)
        batch_op.drop_index(batch_op.f('ix_agro_flight_kml_routes_flight_record_id'))
        batch_op.create_index(batch_op.f('ix_agro_flight_kml_routes_flight_record_id'), ['flight_record_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_agro_flight_kml_routes_file_sha256'))
        batch_op.create_index(batch_op.f('ix_agro_flight_kml_routes_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('agro_flight_kml_routes_route_code_key'), ['route_code'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('agro_flight_kml_routes_flight_record_id_key'), ['flight_record_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('agro_flight_kml_routes_file_sha256_key'), ['file_sha256'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.alter_column('tipo_abastecimento',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
