"""Add nome_equipe to equipe_uvis

Revision ID: 78ea473985fd
Revises: 937343e3998a
Create Date: 2026-01-28 09:58:28.362286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ea473985fd'
down_revision = '937343e3998a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipe_uvis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_equipe', sa.String(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('ix_equipe_uvis_uvis_ordem'))
        batch_op.drop_constraint(batch_op.f('uq_equipe_uvis_slot'), type_='unique')
        batch_op.create_index(batch_op.f('ix_equipe_uvis_nome_equipe'), ['nome_equipe'], unique=False)
        batch_op.create_index('ix_equipe_uvis_uvis_equipe', ['uvis_usuario_id', 'nome_equipe'], unique=False)
        batch_op.create_index('ix_equipe_uvis_uvis_equipe_ordem', ['uvis_usuario_id', 'nome_equipe', 'ordem'], unique=False)
        batch_op.create_unique_constraint('uq_equipe_uvis_equipe_slot', ['uvis_usuario_id', 'nome_equipe', 'ordem'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipe_uvis', schema=None) as batch_op:
        batch_op.drop_constraint('uq_equipe_uvis_equipe_slot', type_='unique')
        batch_op.drop_index('ix_equipe_uvis_uvis_equipe_ordem')
        batch_op.drop_index('ix_equipe_uvis_uvis_equipe')
        batch_op.drop_index(batch_op.f('ix_equipe_uvis_nome_equipe'))
        batch_op.create_unique_constraint(batch_op.f('uq_equipe_uvis_slot'), ['uvis_usuario_id', 'ordem'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_equipe_uvis_uvis_ordem'), ['uvis_usuario_id', 'ordem'], unique=False)
        batch_op.drop_column('nome_equipe')

    # ### end Alembic commands ###
