"""criacao de tabela ordens_servico

Revision ID: 83b552da66d9
Revises: df1b9ae2ae68
Create Date: 2026-03-02 10:32:08.102638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b552da66d9'
down_revision = 'df1b9ae2ae68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('ordens_servico',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    # sa.Column('equipe_id', sa.Integer(), nullable=False),
    # sa.Column('identificador_os', sa.String(length=100), nullable=True),
    # sa.Column('respondido_por', sa.String(length=150), nullable=True),
    # sa.Column('respondido_em', sa.DateTime(), nullable=True),
    # sa.Column('situacao_aplicacao', sa.String(length=100), nullable=True),
    # sa.Column('larva_visualizada', sa.String(length=20), nullable=True),
    # sa.Column('retornar_proxima_semana_monitorar_larvas', sa.String(length=20), nullable=True),
    # sa.Column('distrito_administrativo', sa.String(length=100), nullable=True),
    # sa.Column('nome_rf_ace_responsavel_os', sa.String(length=200), nullable=True),
    # sa.Column('criadouro_os_tipo_volume', sa.Text(), nullable=True),
    # sa.Column('data_aplicacao', sa.Date(), nullable=True),
    # sa.Column('hora_inicio_aplicacao', sa.Time(), nullable=True),
    # sa.Column('hora_termino_aplicacao', sa.Time(), nullable=True),
    # sa.Column('tratamento_adicional_realizado', sa.String(length=20), nullable=True),
    # sa.Column('quantos_quais', sa.Text(), nullable=True),
    # sa.Column('descricao_produto', sa.String(length=200), nullable=True),
    # sa.Column('formulacao_produto', sa.String(length=200), nullable=True),
    # sa.Column('dosagem_g_10l', sa.String(length=50), nullable=True),
    # sa.Column('tipo_aplicacao', sa.String(length=100), nullable=True),
    # sa.Column('quantidade_produto_administrada_ml', sa.Float(), nullable=True),
    # sa.Column('pulverizacao_area_l_ha', sa.Float(), nullable=True),
    # sa.Column('pulverizacao_foco_tempo_estimado_segundos', sa.Float(), nullable=True),
    # sa.Column('pulverizacao_foco_l_min', sa.Float(), nullable=True),
    # sa.Column('prefixo_aeronave_pulverizacao', sa.String(length=100), nullable=True),
    # sa.Column('prefixo_aeronave_monitoramento', sa.String(length=100), nullable=True),
    # sa.Column('quantidade_imagens_registradas', sa.Integer(), nullable=True),
    # sa.Column('ponta_pulverizacao', sa.String(length=100), nullable=True),
    # sa.Column('temperatura_c', sa.Float(), nullable=True),
    # sa.Column('umidade_relativa_pct', sa.Float(), nullable=True),
    # sa.Column('velocidade_vento_kmh', sa.Float(), nullable=True),
    # sa.Column('motivo_nao_realizacao', sa.String(length=255), nullable=True),
    # sa.Column('observacoes', sa.Text(), nullable=True),
    # sa.Column('piloto', sa.String(length=150), nullable=True),
    # sa.Column('assinatura_piloto', sa.Text(), nullable=True),
    # sa.Column('auxiliar', sa.String(length=150), nullable=True),
    # sa.Column('proprietario_ou_preposto', sa.String(length=200), nullable=True),
    # sa.Column('assinatura_proprietario_ou_preposto', sa.Text(), nullable=True),
    # sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    # sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_auxiliar'), ['auxiliar'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_data_aplicacao'), ['data_aplicacao'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_equipe_id'), ['equipe_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_identificador_os'), ['identificador_os'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_piloto'), ['piloto'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_prefixo_aeronave_monitoramento'), ['prefixo_aeronave_monitoramento'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_prefixo_aeronave_pulverizacao'), ['prefixo_aeronave_pulverizacao'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_respondido_em'), ['respondido_em'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_respondido_por'), ['respondido_por'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_situacao_aplicacao'), ['situacao_aplicacao'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_solicitacao_id'), ['solicitacao_id'], unique=True)
    #     batch_op.create_index(batch_op.f('ix_ordens_servico_tipo_aplicacao'), ['tipo_aplicacao'], unique=False)
    #     batch_op.create_index('ix_os_data_aplicacao', ['data_aplicacao'], unique=False)
    #     batch_op.create_index('ix_os_equipe', ['equipe_id'], unique=False)
    #     batch_op.create_index('ix_os_identificador', ['identificador_os'], unique=False)
    #     batch_op.create_index('ix_os_respondido_em', ['respondido_em'], unique=False)
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_index('ix_os_respondido_em')
        batch_op.drop_index('ix_os_identificador')
        batch_op.drop_index('ix_os_equipe')
        batch_op.drop_index('ix_os_data_aplicacao')
        batch_op.drop_index(batch_op.f('ix_ordens_servico_tipo_aplicacao'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_solicitacao_id'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_situacao_aplicacao'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_respondido_por'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_respondido_em'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_prefixo_aeronave_pulverizacao'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_prefixo_aeronave_monitoramento'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_piloto'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_identificador_os'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_equipe_id'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_data_aplicacao'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_auxiliar'))

    op.drop_table('ordens_servico')
    # ### end Alembic commands ###
