"""empty message

Revision ID: 887397110b50
Revises: 78ea473985fd
Create Date: 2026-01-30 10:20:11.796026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887397110b50'
down_revision = '78ea473985fd'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Cria a coluna permitindo valores nulos (temporariamente)
    op.add_column('solicitacoes', sa.Column('area_restrita', sa.Boolean(), nullable=True))
    
    # 2. Preenche todas as linhas existentes com o valor padrão (False)
    op.execute("UPDATE solicitacoes SET area_restrita = False")
    
    # 3. Agora que não existem mais nulos, altera para NOT NULL
    op.alter_column('solicitacoes', 'area_restrita', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_column('area_restrita')

    # ### end Alembic commands ###
