"""ajustes solicitacoes

Revision ID: 937343e3998a
Revises: c956444eccf2
Create Date: 2026-01-20 10:18:00.833991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937343e3998a'
down_revision = 'c956444eccf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipe_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_solicitacoes_equipe_id'), ['equipe_id'], unique=False)
        batch_op.create_foreign_key(None, 'equipes', ['equipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_solicitacoes_equipe_id'))
        batch_op.drop_column('equipe_id')

    # ### end Alembic commands ###
