"""add veiculos equipamento polimorfico

Revision ID: 9922f618dc90
Revises: 9f00e9db7721
Create Date: 2026-02-23 10:34:54.266853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9922f618dc90'
down_revision = '9f00e9db7721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('veiculos',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('frota', sa.String(length=20), nullable=False),
    # sa.Column('operacao', sa.String(length=30), nullable=False),
    # sa.Column('placa', sa.String(length=10), nullable=False),
    # sa.Column('responsavel', sa.String(length=120), nullable=True),
    # sa.Column('km_atual', sa.Float(), nullable=False),
    # sa.Column('km_prox_revisao', sa.Float(), nullable=True),
    # sa.Column('revisao_marcada_em', sa.DateTime(), nullable=True),
    # sa.Column('revisao_obs', sa.String(length=255), nullable=True),
    # sa.ForeignKeyConstraint(['id'], ['equipamentos.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('veiculos', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_veiculos_frota'), ['frota'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_veiculos_operacao'), ['operacao'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_veiculos_placa'), ['placa'], unique=True)
    #     batch_op.create_index(batch_op.f('ix_veiculos_responsavel'), ['responsavel'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_veiculos_revisao_marcada_em'), ['revisao_marcada_em'], unique=False)
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculos_revisao_marcada_em'))
        batch_op.drop_index(batch_op.f('ix_veiculos_responsavel'))
        batch_op.drop_index(batch_op.f('ix_veiculos_placa'))
        batch_op.drop_index(batch_op.f('ix_veiculos_operacao'))
        batch_op.drop_index(batch_op.f('ix_veiculos_frota'))

    op.drop_table('veiculos')
    # ### end Alembic commands ###
