"""formulario_veiculo

Revision ID: 9e93b678aa02
Revises: 11a05840b7c3
Create Date: 2026-03-05 09:49:49.613092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e93b678aa02'
down_revision = '11a05840b7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_nf_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('check_diario', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('foto_painel_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('assinatura_piloto', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.drop_column('assinatura_piloto')
        batch_op.drop_column('foto_painel_path')
        batch_op.drop_column('check_diario')
        batch_op.drop_column('foto_nf_path')

    # ### end Alembic commands ###
