"""Refatora equipamentos para herança polimorfica

Revision ID: 9f00e9db7721
Revises: c7248594d6e9
Create Date: 2026-02-20 10:32:07.401322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f00e9db7721'
down_revision = 'c7248594d6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drones_registro_anatel'))
        batch_op.create_index(batch_op.f('ix_drones_registro_anatel'), ['registro_anatel'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drones_registro_anatel'))
        batch_op.create_index(batch_op.f('ix_drones_registro_anatel'), ['registro_anatel'], unique=True)

    # ### end Alembic commands ###
