"""ajustando colunas faltantes

Revision ID: a44146ee66f1
Revises: 1330e7e67220
Create Date: 2026-03-13 12:03:53.341041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44146ee66f1'
down_revision = '1330e7e67220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_abastecimento', sa.String(length=100), nullable=True))

    with op.batch_alter_table('checklists_semanais_drone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_semanais_drone_nome_responsavel'), ['nome_responsavel'], unique=False)

    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.drop_column('litros')
        batch_op.drop_column('foto_nf_path')
        batch_op.drop_column('abasteceu')
        batch_op.drop_column('km_no_abastecimento')
        batch_op.drop_column('valor_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('km_no_abastecimento', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('abasteceu', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto_nf_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('litros', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('checklists_semanais_drone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_semanais_drone_nome_responsavel'))

    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.drop_column('tipo_abastecimento')

    # ### end Alembic commands ###
