"""atualizando banco

Revision ID: a5f137cd1851
Revises: c10d6513ba77
Create Date: 2026-03-10 11:01:45.773929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f137cd1851'
down_revision = 'c10d6513ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_fazendas_enderecos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.drop_column('qtd_fazendas_enderecos')

    # ### end Alembic commands ###
