"""fix drone relationships and add snapshots

Revision ID: a6d569185386
Revises: 10995bc0178b
Create Date: 2026-03-03 09:18:19.525858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d569185386'
down_revision = '10995bc0178b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drone_denominacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drone_monitoramento_denominacao', sa.String(length=100), nullable=True))
        batch_op.drop_column('drone_renomacao')
        batch_op.drop_column('drone_monitoramento_renomacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drone_monitoramento_renomacao', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('drone_renomacao', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('drone_monitoramento_denominacao')
        batch_op.drop_column('drone_denominacao')

    # ### end Alembic commands ###
