"""atualizacao para checklists semanais

Revision ID: be82e9f30bff
Revises: a5f137cd1851
Create Date: 2026-03-11 10:40:29.101345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be82e9f30bff'
down_revision = 'a5f137cd1851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists_semanais_drone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('helices_status', sa.Boolean(), nullable=True),
    sa.Column('condicao_helices', sa.Text(), nullable=True),
    sa.Column('tanque', sa.Boolean(), nullable=True),
    sa.Column('trem_pouso', sa.Boolean(), nullable=True),
    sa.Column('cameras', sa.Boolean(), nullable=True),
    sa.Column('condicao_estrutura', sa.Text(), nullable=True),
    sa.Column('carregador_controle', sa.Boolean(), nullable=True),
    sa.Column('baterias', sa.Boolean(), nullable=True),
    sa.Column('condicao_carregador_bateria', sa.Text(), nullable=True),
    sa.Column('cabos_carregador', sa.Boolean(), nullable=True),
    sa.Column('correia_pescoco', sa.Boolean(), nullable=True),
    sa.Column('condicao_cabos_correia', sa.Text(), nullable=True),
    sa.Column('num_baterias', sa.Integer(), nullable=True),
    sa.Column('num_baterias_wb', sa.Integer(), nullable=True),
    sa.Column('observacoes_equipamento', sa.Text(), nullable=True),
    sa.Column('assinatura_piloto', sa.Text(), nullable=True),
    sa.Column('nome_responsavel', sa.String(length=150), nullable=True),
    sa.Column('assinatura_responsavel', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.ForeignKeyConstraint(['piloto_id'], ['pilotos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklists_semanais_drone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_semanais_drone_data_registro'), ['data_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_semanais_drone_drone_id'), ['drone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_semanais_drone_nome_responsavel'), ['nome_responsavel'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_semanais_drone_piloto_id'), ['piloto_id'], unique=False)

    op.create_table('checklists_semanais_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('km_leitura', sa.Float(), nullable=False),
    sa.Column('farois_funcionando', sa.Boolean(), nullable=True),
    sa.Column('setas_funcionando', sa.Boolean(), nullable=True),
    sa.Column('lanternas_funcionando', sa.Boolean(), nullable=True),
    sa.Column('piscaalerta_funcionando', sa.Boolean(), nullable=True),
    sa.Column('condicao_luzes_direcao', sa.Text(), nullable=True),
    sa.Column('luz_painel', sa.Boolean(), nullable=True),
    sa.Column('condicao_luz_painel', sa.Text(), nullable=True),
    sa.Column('limpador_parabrisa', sa.Boolean(), nullable=True),
    sa.Column('agua_radiador', sa.Boolean(), nullable=True),
    sa.Column('fluido_freio', sa.Boolean(), nullable=True),
    sa.Column('oleo_motor', sa.Boolean(), nullable=True),
    sa.Column('condicao_itens_manutencao', sa.Text(), nullable=True),
    sa.Column('vidros', sa.Boolean(), nullable=True),
    sa.Column('retrovisores', sa.Boolean(), nullable=True),
    sa.Column('condicao_vidros_retrovisores', sa.Text(), nullable=True),
    sa.Column('pneus', sa.Boolean(), nullable=True),
    sa.Column('estepe', sa.Boolean(), nullable=True),
    sa.Column('macaco', sa.Boolean(), nullable=True),
    sa.Column('triangulo', sa.Boolean(), nullable=True),
    sa.Column('chave_roda', sa.Boolean(), nullable=True),
    sa.Column('condicao_pneus_estepe', sa.Text(), nullable=True),
    sa.Column('extintor', sa.Boolean(), nullable=True),
    sa.Column('cinto_seguranca', sa.Boolean(), nullable=True),
    sa.Column('condicao_itens_seguranca', sa.Text(), nullable=True),
    sa.Column('alarme', sa.Boolean(), nullable=True),
    sa.Column('ar_condicionado', sa.Boolean(), nullable=True),
    sa.Column('radio', sa.Boolean(), nullable=True),
    sa.Column('condicao_itens_carro_interno', sa.Text(), nullable=True),
    sa.Column('giroflex', sa.Boolean(), nullable=True),
    sa.Column('isqueiro', sa.Boolean(), nullable=True),
    sa.Column('carregador', sa.Boolean(), nullable=True),
    sa.Column('condicao_giroflex_isqueiro_carregador', sa.Text(), nullable=True),
    sa.Column('lataria_frontal', sa.Boolean(), nullable=True),
    sa.Column('lataria_lateral', sa.Boolean(), nullable=True),
    sa.Column('lataria_traseira', sa.Boolean(), nullable=True),
    sa.Column('condicao_lataria', sa.Text(), nullable=True),
    sa.Column('lataria_porta_frontal', sa.Boolean(), nullable=True),
    sa.Column('lataria_porta_traseira', sa.Boolean(), nullable=True),
    sa.Column('lataria_porta_lateral', sa.Boolean(), nullable=True),
    sa.Column('condicao_lataria_portas', sa.Text(), nullable=True),
    sa.Column('parachoque_frontal', sa.Boolean(), nullable=True),
    sa.Column('parachoque_traseiro', sa.Boolean(), nullable=True),
    sa.Column('condicao_itens_carro_externo', sa.Text(), nullable=True),
    sa.Column('assinatura_piloto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['piloto_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklists_semanais_veiculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_semanais_veiculo_data_registro'), ['data_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_semanais_veiculo_piloto_id'), ['piloto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_semanais_veiculo_veiculo_id'), ['veiculo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists_semanais_veiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_semanais_veiculo_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_semanais_veiculo_piloto_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_semanais_veiculo_data_registro'))

    op.drop_table('checklists_semanais_veiculo')
    with op.batch_alter_table('checklists_semanais_drone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_semanais_drone_piloto_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_semanais_drone_nome_responsavel'))
        batch_op.drop_index(batch_op.f('ix_checklists_semanais_drone_drone_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_semanais_drone_data_registro'))

    op.drop_table('checklists_semanais_drone')
    # ### end Alembic commands ###
