"""empty message

Revision ID: bf8582b1beb6
Revises: 5d7e9a1c3b20
Create Date: 2026-09-18 09:47:38.961525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8582b1beb6'
down_revision = '5d7e9a1c3b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('denuncias_protocolo_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('denuncias_solicitacao_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_denuncias_atualizado_em'), ['atualizado_em'], unique=False)

    with op.batch_alter_table('estoque_pecas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('estoque_pecas_numero_serie_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_estoque_pecas_numero_serie'))
        batch_op.create_index(batch_op.f('ix_estoque_pecas_numero_serie'), ['numero_serie'], unique=True)
        batch_op.create_index(batch_op.f('ix_estoque_pecas_atualizado_em'), ['atualizado_em'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_pecas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_pecas_atualizado_em'))
        batch_op.drop_index(batch_op.f('ix_estoque_pecas_numero_serie'))
        batch_op.create_index(batch_op.f('ix_estoque_pecas_numero_serie'), ['numero_serie'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('estoque_pecas_numero_serie_key'), ['numero_serie'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_denuncias_atualizado_em'))
        batch_op.create_unique_constraint(batch_op.f('denuncias_solicitacao_id_key'), ['solicitacao_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('denuncias_protocolo_key'), ['protocolo'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)

    # ### end Alembic commands ###
