"""adicionando campo de total de enderecos

Revision ID: c10d6513ba77
Revises: d4ea9c7cb902
Create Date: 2026-03-09 10:51:06.996590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10d6513ba77'
down_revision = 'd4ea9c7cb902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_fazendas_enderecos', sa.Integer(), nullable=True))
        batch_op.drop_column('qtd_fazendas_endereços')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_fazendas_endereços', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('qtd_fazendas_enderecos')

    # ### end Alembic commands ###
