"""atualizacao banco prod

Revision ID: c6925a2c28d0
Revises: be82e9f30bff
Create Date: 2026-03-12 09:17:19.486600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6925a2c28d0'
down_revision = 'be82e9f30bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists_semanais_drone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_piloto_responsavel', sa.Text(), nullable=True))
        batch_op.drop_column('assinatura_responsavel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists_semanais_drone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_responsavel', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('assinatura_piloto_responsavel')

    # ### end Alembic commands ###
