"""adicionar fotos os

Revision ID: c6a066e20bc3
Revises: 3a2c4e5f6a7b
Create Date: 2026-03-26 11:39:19.134559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a066e20bc3'
down_revision = '3a2c4e5f6a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dji_flight_records', schema=None) as batch_op:
        # batch_op.drop_constraint(batch_op.f('dji_flight_records_fingerprint_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_dji_flight_records_fingerprint'))
        batch_op.create_index(batch_op.f('ix_dji_flight_records_fingerprint'), ['fingerprint'], unique=True)

    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_principal', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('outras_imagens', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('video')
        batch_op.drop_column('outras_imagens')
        batch_op.drop_column('imagem_principal')

    with op.batch_alter_table('dji_flight_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dji_flight_records_fingerprint'))
        batch_op.create_index(batch_op.f('ix_dji_flight_records_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('dji_flight_records_fingerprint_key'), ['fingerprint'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
