"""add equipe_uvis_nome to solicitacoes

Revision ID: c7248594d6e9
Revises: 15d9ec71945b
Create Date: 2026-02-09 10:10:58.065544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7248594d6e9'
down_revision = '15d9ec71945b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('equipe_uvis_nome', sa.String(length=100), nullable=True))
        #batch_op.create_index(batch_op.f('ix_solicitacoes_equipe_uvis_nome'), ['equipe_uvis_nome'], unique=False)
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_equipe_uvis_nome'))
        batch_op.drop_column('equipe_uvis_nome')

    # ### end Alembic commands ###
