"""equipe

Revision ID: c956444eccf2
Revises: 2d00b144d9e1
Create Date: 2026-01-19 15:00:55.062735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c956444eccf2'
down_revision = '2d00b144d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe_pilotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['piloto_id'], ['pilotos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipe_id', 'papel', name='uq_equipe_papel_unico'),
    sa.UniqueConstraint('equipe_id', 'piloto_id', name='uq_equipe_piloto_unico')
    )
    with op.batch_alter_table('equipe_pilotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipe_pilotos_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index('ix_equipe_pilotos_equipe', ['equipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipe_pilotos_equipe_id'), ['equipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipe_pilotos_papel'), ['papel'], unique=False)
        batch_op.create_index('ix_equipe_pilotos_piloto', ['piloto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipe_pilotos_piloto_id'), ['piloto_id'], unique=False)

    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('regiao', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ativa', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('criada_em', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_equipes_ativa'), ['ativa'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipes_criada_em'), ['criada_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipes_regiao'), ['regiao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipes_regiao'))
        batch_op.drop_index(batch_op.f('ix_equipes_criada_em'))
        batch_op.drop_index(batch_op.f('ix_equipes_ativa'))
        batch_op.drop_column('criada_em')
        batch_op.drop_column('ativa')
        batch_op.drop_column('regiao')
        batch_op.drop_column('descricao')

    with op.batch_alter_table('equipe_pilotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipe_pilotos_piloto_id'))
        batch_op.drop_index('ix_equipe_pilotos_piloto')
        batch_op.drop_index(batch_op.f('ix_equipe_pilotos_papel'))
        batch_op.drop_index(batch_op.f('ix_equipe_pilotos_equipe_id'))
        batch_op.drop_index('ix_equipe_pilotos_equipe')
        batch_op.drop_index(batch_op.f('ix_equipe_pilotos_criado_em'))

    op.drop_table('equipe_pilotos')
    # ### end Alembic commands ###
