"""ajuste no models pra encaixar o drone na OS

Revision ID: cc0e21916d4c
Revises: 83b552da66d9
Create Date: 2026-03-02 11:59:00.395736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0e21916d4c'
down_revision = '83b552da66d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drone_renomacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drone_modelo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drone_numero_serie', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drone_registro_anatel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('drone_registro_anac', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_ordens_servico_drone_id'), ['drone_id'], unique=False)
        batch_op.create_index('ix_os_equipe_drone', ['equipe_id', 'drone_id'], unique=False)
        batch_op.create_foreign_key(None, 'drones', ['drone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_os_equipe_drone')
        batch_op.drop_index(batch_op.f('ix_ordens_servico_drone_id'))
        batch_op.drop_column('drone_registro_anac')
        batch_op.drop_column('drone_registro_anatel')
        batch_op.drop_column('drone_numero_serie')
        batch_op.drop_column('drone_modelo')
        batch_op.drop_column('drone_renomacao')
        batch_op.drop_column('drone_id')

    # ### end Alembic commands ###
