"""atualizão null km final

Revision ID: d4ea9c7cb902
Revises: 9e93b678aa02
Create Date: 2026-03-05 10:54:19.942285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ea9c7cb902'
down_revision = '9e93b678aa02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.alter_column('km_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_veiculo', schema=None) as batch_op:
        batch_op.alter_column('km_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
