"""criação e remoção de campos

Revision ID: fd9c1a47ec4c
Revises: a6d569185386
Create Date: 2026-03-03 11:48:05.981573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9c1a47ec4c'
down_revision = 'a6d569185386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('pulverizacao_foco_l_min')
        batch_op.drop_column('pulverizacao_foco_tempo_estimado_segundos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pulverizacao_foco_tempo_estimado_segundos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pulverizacao_foco_l_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
